version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:12.5-alpine
    environment:
      POSTGRES_DB: diecast_collector_dev
      POSTGRES_USER: ${POSTGRES_USER:-diecast_collector}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-diecast_collector}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
