apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.name }}
  labels:
    app: {{ .Chart.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Chart.name }}
    spec:
      imagePullSecrets:
        - name: gitlab-auth-{{ .Chart.name }}
      containers:
        - name: {{ .Chart.name }}
          envFrom:
            - configMapRef:
                name: {{ .Chart.name }}-config
          image: {{ .Values.image.repository }}/{{ .Values.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          startupProbe: # the application will have a maximum of 5 minutes (30 * 10 = 300s) to finish its startup
            httpGet:
              path: /health
              port: 8081
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 3
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 3
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
