datasources:
  default:
    url: jdbc:tc:postgresql:12:///postgres
    driverClassName: org.testcontainers.jdbc.ContainerDatabaseDriver
    dialect: POSTGRES
flyway:
  datasources:
    default:
      baseline-on-migrate: true
      locations: classpath:db/migration
jooq:
  datasources:
    default:
      sql-dialect: POSTGRES