---
micronaut:
  application:
    name: micronaut-rest-example-postgres
  executors:
    io:
      type: fixed
      nThreads: 75
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

endpoints:
  all:
    port: 8081
  health:
    enabled: true
---
datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/diecast_collector_dev`}
    driverClassName: ${JDBC_DRIVER:org.postgresql.Driver}
    username: ${JDBC_USER:diecast_collector}
    password: ${JDBC_PASSWORD:diecast_collector}
flyway:
  datasources:
    default:
      baseline-on-migrate: true
      locations: classpath:db/migration
jooq:
  datasources:
    default:
      sql-dialect: POSTGRES